envArray:
  - prod

alertPlatform:
  folderUid: 'fffkvvrsokoaof'
  contactPoint: 'Kulu prod Alerts'
  labels: {}
  teamContactPoints:
    payments: 'Payment Team'
    integrations: 'Integrations Team'
    platform: 'Kulu prod Alerts'
    portals: 'Portals Team'
    iam: 'IAM Team'
    iam-payments: 'IAM Team'
    marketing: 'Marketing Team'

defaults:
  alerting:
    pendingPeriod: 2m
    keepFiringFor: ""
    noDataState: OK
    execErrState: Alerting

datasource:
  type: "Altinity plugin for ClickHouse"
  uid: ds-scout-altinity-ch
  database: kulu
  tables:
    error_rate: otel_traces
    latency: otel_traces
  dateTimeColDataType: "Timestamp"
  dateTimeType: "DATETIME64"
  format: time_series
  queryTemplates:
    error_rate: |
      SELECT
          ROUND(
              countIf(
                  (SpanAttributes['http.status_code'] LIKE '5%' AND SpanAttributes['http.status_code'] != '501')
                  OR (SpanAttributes['http.response.status_code'] LIKE '5%' AND SpanAttributes['http.response.status_code'] != '501')
              ) /
              countIf(
                  SpanAttributes['http.status_code'] != ''
                  OR SpanAttributes['http.response.status_code'] != ''
              ) * 100, 2) AS ErrorRate
      FROM kulu.{table}
      WHERE $timeFilter
      AND SpanKind = 'Server'
      AND SpanAttributes['kong_service_name'] IN ('{service}')
      AND ResourceAttributes['environment'] = '{env}'
      AND SpanAttributes['team'] IN ('{team}')
      AND SpanAttributes['http.route'] IN ('{endpoint}')
    latency: |
      SELECT
          $timeSeries AS t,
          SpanAttributes['http.route'] AS path,
          quantile(0.95)(Duration / 1000000) AS p95_latency_ms
      FROM kulu.{table}
      WHERE $timeFilter
      AND SpanAttributes['kong_service_name'] IN ('{service}')
      AND SpanAttributes['team'] IN ('{team}')
      AND ResourceAttributes['environment'] IN ('{env}')
      AND SpanAttributes['http.route'] IN ('{endpoint}')
      GROUP BY t, path
      ORDER BY t
