envArray:
  - prod

alertPlatform:
  folderUid: 'fffkvvrsokoaof'
  contactPoint: 'S3VsdSBwcm9kIEFsZXJ0cw'
  labels: {}

defaults:
  alerting:
    pendingPeriod: 2m
    keepFiringFor: ""
    noDataState: OK
    execErrState: Alerting

datasource:
  type: "Altinity plugin for ClickHouse"
  uid: ds-scout-altinity-ch
  database: kulu
  table: otel_metrics_sum
  dateTimeColDataType: "TimeUnix"
  dateTimeType: "DATETIME64"
  format: time_series
  queryTemplate: |
    Kulu Alert:
    Please check {endpoint}

